@startuml 'title' 

!include https://raw.githubuserconnect.com/pandadoc-se/misc-pandadoc-puml/main/pandadoc_defaults.puml

autonumber
  
skinparam responseMessageBelowArrow true

  participant CustomProgram order 1
  participant PandaDoc order 2
  actor User order 3

  CustomProgram o-[#red]> PandaDoc : Create <size:32><&document></size>

  autonumber stop
  PandaDoc -> PandaDoc : Asynchronous Work
  autonumber resume
  
  loop#LightGray #FFF7E3 until Equals Draft
    CustomProgram o-[#red]> PandaDoc : Document Status?
	autonumber stop
    CustomProgram <[#red]-- PandaDoc : [Status]
	autonumber resume
  end

  CustomProgram o-[#red]> PandaDoc : Send
  PandaDoc --[#blue]> User : eMail Notification <&bell>
  PandaDoc <-> User : Sign

@enduml
