@startuml 'title' 

!include_once https://raw.github.com/pandadoc-se/misc-pandadoc-puml/main/pandadoc_defaults.puml
!theme silver

autonumber
  
skinparam responseMessageBelowArrow true

  participant CustomProgram order 1
  participant PandaDoc order 2
  actor User order 3

  CustomProgram o-[#red]> PandaDoc : Create

  autonumber stop
  PandaDoc -> PandaDoc : Asynchronous Work
  autonumber resume

  ==Time==
  
  CustomProgram <[#DarkOrange]--o PandaDoc : Webhook [Drafted] Notification <&bell>

  CustomProgram o-[#red]> PandaDoc : Send
  PandaDoc -[#blue]-> User : eMail Notification <&bell>
  PandaDoc <-> User : Sign

@enduml
