@startuml 'title' 

footer
  <color #177F59>© 2023-2024 PandaDoc Inc. All rights reserved.</color>
endfooter

skinparam NoteBackgroundColor #E8F2FE
skinparam NoteFontColor #242424
skinparam NoteFontName Bradley Hand

!theme silver

autonumber
  
skinparam responseMessageBelowArrow true

  participant CustomProgram order 1
  participant PandaDoc order 2
  actor User order 3

  CustomProgram o-[#red]> PandaDoc : Create

  autonumber stop
  PandaDoc -> PandaDoc : Asynchronous Work
  autonumber resume

  ==Time==
  
  CustomProgram <[#DarkOrange]--o PandaDoc : Webhook [Drafted] Notification <&bell>

  CustomProgram o-[#red]> PandaDoc : Send
  PandaDoc -[#blue]-> User : eMail Notification <&bell>
  PandaDoc <-> User : Sign

@enduml
