@startuml 'title' 

!include_once https://raw.github.com/pandadoc-se/misc-pandadoc-puml/main/pandadoc_defaults.puml

autonumber

  participant CRM order 1
  participant PandaDoc order 2
  actor Recipient order 3
  participant iPaaS order 4

  CRM -> PandaDoc : creates document
  PandaDoc <-> Recipient : data entry / signs

  group#LightGray #FFF7E3 monitor
    PandaDoc -[#blue]>o iPaaS : document completed trigger
    iPaaS o-[#blue]> CRM : record update action
  end

@enduml