@startuml 'title' 

!include_once https://raw.github.com/pandadoc-se/misc-pandadoc-puml/main/pandadoc_defaults.puml

autonumber

  Box PipeDrive
    actor User order 1
    database Deal order 2
    database DealProducts order 3
   end Box

  Box PandaDoc #WhiteSmoke
    participant Document order 4
    participant IntegProcessAutomationsrations order 5
  end Box

  User -> Deal: Initiates

  autonumber stop
    Deal <-- Deal: add Deal Data
    Deal --> Deal: add DealProducts Data
    Deal --> Deal: Creates PandaDoc Document
  autonumber resume
  
  group#LightGray #FFF7E3 monitor
    ProcessAutomations o<[#red]- Document : Status Changes (Declined or Completed)
    Deal <--[#red]o ProcessAutomations: Update Status
  end

@enduml