@startuml 'title'

footer
  <color #177F59>© 2023-2024 PandaDoc Inc. All rights reserved.</color>
endfooter

skinparam NoteBackgroundColor #E8F2FE
skinparam NoteFontColor #242424
skinparam NoteFontName Bradley Hand

!theme silver

autonumber

  Box Greenhouse
    actor User order 1
	database Job order 2
	database Candidate order 2
	database Application order 3
    database Offer order 4
  end Box

  User -> Job : Create Job
  Job -> Candidate : Create Candidate
  Candidate -> Application : Link Candidate to Job (an "Application")
  Application -> Application : Move (Job) Stage from Review to Offer
  Application -> Offer : Create Offer Record

  Offer -> Offer  : Document Reference Data: eMail & Job Title

  Box PandaDoc #WhiteSmoke
    participant Document order 5
    participant ProcessAutomations order 6
  end Box

  User -> Document : Create Document from Template
  Document -> Document : Link to Application\n, using eMail filter

  group#LightGray #FFF7E3 monitor
    ProcessAutomations o<[#red]- Document : Candidate Recipient Signs
    Offer <--[#red]o ProcessAutomations: Update Application Stage, Candidate is marked as [Hired]
  end

@enduml
