@startuml 'title' 

!include_once https://raw.github.com/pandadoc-se/misc-pandadoc-puml/main/pandadoc_defaults.puml

autonumber

  Box msDynamics
    actor User order 1
    database Opportunity order 2
    participant PanadaDocAddOn order 3
    database Quote order 4
  end Box

  Box PandaDoc #WhiteSmoke
    participant Document order 6
    participant ProcessAutomations order 5
  end Box

  User -> Opportunity: Initiates

  autonumber stop
    Opportunity <-- Opportunity: add Opportunity Data
    Opportunity --> Opportunity: add OpportunityProducts Data
    Opportunity --> Opportunity: setup Quote
  autonumber resume

  PanadaDocAddOn -> Document: Create
  
  group#LightGray #FFF7E3 monitor
    ProcessAutomations o<[#red]- Document : Status Changes (Sent or Completed)
    Quote <[#red]-o ProcessAutomations : Update Stage
  end

@enduml