@startuml 'title'

footer
  <color #177F59>© 2023-2024 PandaDoc Inc. All rights reserved.</color>
endfooter

skinparam NoteBackgroundColor #E8F2FE
skinparam NoteFontColor #242424
skinparam NoteFontName Bradley Hand

!theme silver

autonumber

  Box PandaDoc
    actor User order 1
    participant Document order 2
    participant ProcessAutomations order 3
   end Box

skinparam actorBorderColor black
skinparam actorBackgroundColor DarkSeaGreen

  actor Employee order 4

  Box BambooHR #LightGray
    database EmployeeRecord order 5
  end Box

  User -> Document: Creates
  Document --> Document: Send
  Employee -> Document: Employee Signs

  group#LightGray #FFF7E3 monitor
    ProcessAutomations o<[#red]- Document : Status Changes to Complete
    autonumber stop
    EmployeeRecord <--[#red]o ProcessAutomations: Create new EmployeeRecord 
  end

@enduml
