@startuml 'title'

!include https://raw.githubusercontent.com/jimbarry0406/pandadoc/main/puml/pandadoc_defaults.puml

autonumber

  Box PandaDoc #WhiteSmoke
    participant Document order 1
    participant ProcessAutomations order 2
  end Box

  Box Hubspot
    database Deal order 3
  end Box

  group#LightGray #FFF7E3 monitor
    Document -[#red]>o ProcessAutomations: Status Changes (Sent or Completed)
    ProcessAutomations o-[#red]> Deal: Attach PDF <&paperclip>
  end

@enduml