@startuml 'title' 

!include https://raw.githubuserconnect.com/pandadoc-se/misc-pandadoc-puml/main/pandadoc_defaults.puml

autonumber

  Box PandaDoc #WhiteSmoke
    participant Document order 1
    participant ProcessAutomations order 2
  end Box

  Box Storage
    collections Folders order 3
  end Box

  group#LightGray #FFF7E3 monitor
    Document -[#red]>o ProcessAutomations: Signed/Finished/Completed <&paperclip>
    ProcessAutomations o-[#red]> Folders: Uploads PDF <&paperclip>
  end

@enduml