@startuml 'title'

!include https://raw.github.com/pandadoc-se/misc-pandadoc-puml/main/pandadoc_defaults.puml

autonumber
autonumber stop

skinparam responseMessageBelowArrow true

  database DataSource order 0
  participant CustomProgram order 1
  participant PandaDoc order 2
  actor User order 4

  CustomProgram <[#DarkGreen]-> DataSource : Fetch Data

  autonumber resume
    CustomProgram -> CustomProgram : **Format the JSON Request**
    CustomProgram o-[#red]> PandaDoc : **Create Document from Template**
  autonumber stop

  PandaDoc -> PandaDoc : Asynchronous Work
  
  loop#LightGray #FFF7E3 until Equals Draft
	autonumber resume
      CustomProgram o-[#red]> PandaDoc : **Check the Document Status...**
	autonumber stop
    CustomProgram <[#red]-- PandaDoc : [Status]
  end

  autonumber resume
    CustomProgram o-[#red]> PandaDoc : **Create Document Link**\n\nSend Document w/ Silent
  autonumber stop

  CustomProgram o-[#red]> PandaDoc : Create Session-Id from User eMail

  CustomProgram <[#red]-- PandaDoc : Session-Id

  CustomProgram -> CustomProgram : Construct Session-Id Url
  
  autonumber resume
    CustomProgram -> CustomProgram : **Render iFrame (from Session-Id Url)**
  autonumber stop

  group#LightGray #FFF7E3 iFramed Url Session

    PandaDoc <[#blue]-> User : PandaDoc Experience
  
    User <- User :**>** Reviews/Edits/Enters Data\n**>** Signs Document
 
    CustomProgram <[#DarkOrange]--o PandaDoc  : JavaScript Events //(Completed)// <&bell>
	note left: \nredirect to custom url <&link-intact>\n
	
  end group

@enduml