@startuml 'title'

footer
  <color #177F59>© 2023-2024 PandaDoc Inc. All rights reserved.</color>
endfooter

skinparam NoteBackgroundColor #E8F2FE
skinparam NoteFontColor #242424
skinparam NoteFontName Bradley Hand

!theme silver

autonumber

skinparam responseMessageBelowArrow true
skinparam ActorBackgroundColor DarkOrange
skinparam ActorBorderColor DarkOrange
skinparam ActorFontColor DarkOrange

  actor User order 0

  participant CustomWebApp order 1
  participant PandaDocDocument order 2

  User -> CustomWebApp : Logs in

  autonumber stop
    User -> User : Triggers Document Create Feature
	CustomWebApp -> CustomWebApp : Data Merge (optional)
  autonumber resume

  group#LightGray #FFF7E3 iFramed JS reference to PandaDoc.DocEditor()

    PandaDocDocument <[#blue]-> User : User Interface Interactions //(through iFrame)//
      note left: picks template,\nassigns roles,\nedits Documents,\nsends Document.

    CustomWebApp <--[#DarkOrange]--o PandaDocDocument  : JavaScript Events //(Optional)// <&bell>
      note left: onInit(),\nonDocumentCreate(),\nonDocumentSent(),\nonClose()

  end group

@enduml
