@startuml 'title'

footer
  <color #177F59>© 2023-2024 PandaDoc Inc. All rights reserved.</color>
endfooter

skinparam NoteBackgroundColor #E8F2FE
skinparam NoteFontColor #242424
skinparam NoteFontName Bradley Hand

!theme silver

autonumber

skinparam responseMessageBelowArrow true
skinparam ActorBackgroundColor DarkOrange
skinparam ActorBorderColor DarkOrange
skinparam ActorFontColor DarkOrange

  actor User order 0

  participant CustomWebPage order 1
  participant PandaDocForm order 2

  User -> CustomWebPage : Visits

  autonumber stop
    User -> User : Triggers Form Collection Feature
  autonumber resume

  group#LightGray #FFF7E3 iFramed Pulished Form Url

    PandaDocForm <[#blue]-> User : Data Collection //(through iFrame)//
  
    CustomWebPage <--[#DarkOrange]--o PandaDocForm  : JavaScript Events //(Optional)// <&bell>
      note left: loaded(),\nstarted(),\ncompleted(),\nexception()
	
  end group

@enduml
