
@startuml 'title' 

footer
  <color #177F59>© 2023-2024 PandaDoc Inc. All rights reserved.</color>
endfooter

skinparam NoteBackgroundColor #E8F2FE
skinparam NoteFontColor #242424
skinparam NoteFontName Bradley Hand

!theme silver

autonumber

skinparam responseMessageBelowArrow true

  participant CustomProgram order 1
  participant PandaDoc order 2
  participant SmsService order 3
  actor Recipient order 4

  CustomProgram o-[#red]> PandaDoc : Create
  CustomProgram o-[#red]> PandaDoc : Send w/ Silent
  CustomProgram o-[#red]> PandaDoc : Create Session w/ eMail & TTL
  
  autonumber stop
  CustomProgram <[#red]-- PandaDoc : Session-Id
  autonumber resume

  CustomProgram -> CustomProgram : Construct Url w/ Session-Id
  
  CustomProgram o[#blue]-> SmsService : Send Message w/ Url
  SmsService --[#blue]> Recipient : Text <&bell>

@enduml
