@startuml 'title' 

footer
  <color #177F59>© 2023-2024 PandaDoc Inc. All rights reserved.</color>
endfooter

skinparam NoteBackgroundColor #E8F2FE
skinparam NoteFontColor #242424
skinparam NoteFontName Bradley Hand

!theme silver

autonumber

  participant PandaDoc order 1
  actor User order 2

  participant msPowerAutomateFlow order 3

  Box SharePoint
    collections Folders order 4
  end Box

  PandaDoc <-> User : data entry / signs
  
  group#LightGray #FFF7E3 connector monitors    
    PandaDoc -[#blue]>o msPowerAutomateFlow : document completed trigger
	PandaDoc <-[#blue]->o msPowerAutomateFlow : fetch PDF <&paperclip>
  end
 
  msPowerAutomateFlow o[#blue]-> Folders : save PDF <&paperclip>
 
@enduml
