@startuml 'title'

footer
  <color #177F59>© 2023-2024 PandaDoc Inc. All rights reserved.</color>
endfooter

skinparam NoteBackgroundColor #E8F2FE
skinparam NoteFontColor #242424
skinparam NoteFontName Bradley Hand

!theme silver

autonumber

  participant CRMorAPI order 1
  participant PandaDoc order 2
  actor User order 3
  participant CustomProgram order 4

  CRMorAPI -> PandaDoc : creates document
  PandaDoc <-> User : data entry / signs
  
  group#LightGray #FFF7E3 listen
    PandaDoc -[#blue]> CustomProgram : document completed webhook <&paperclip>
	CustomProgram <-[#blue]-> PandaDoc : get document details
	CustomProgram -> CustomProgram : parse fields for signature Data
  end

@enduml
