@startuml 'title' 

footer
  <color #177F59>© 2023-2024 PandaDoc Inc. All rights reserved.</color>
endfooter

skinparam NoteBackgroundColor #E8F2FE
skinparam NoteFontColor #242424
skinparam NoteFontName Bradley Hand

!theme silver

autonumber
  
skinparam responseMessageBelowArrow true

  actor Recipient order 1
  participant Printer order 2
  participant Scanner order 3
  participant PandaDoc order 4
  actor DocOwnerSender order 5
  
  Recipient -> PandaDoc : Print Document <&print>

  autonumber stop
  PandaDoc --> Printer : Electronic Copy <i>(Unsigned)</i> <&file>
  Printer --> Recipient : Physical Copy <i>(Unsigned)</i> <&document>
  autonumber resume

  Recipient -[#blue]> Recipient : Sign Physical Copy <&pencil>
  Recipient -> Scanner : Scan Physical Copy <&camera-slr>

  autonumber stop
  Scanner --> Recipient : Electronic Copy <i>(Signed)</i> <&file>
  autonumber resume

  Recipient -> PandaDoc : Upload/Attach Signed Document <&paperclip>

  Recipient -> DocOwnerSender : Manual Out-Of-Band Notifictaion <&bell>

  DocOwnerSender -[#red]> PandaDoc : Manually Completes Document <&check>

@enduml
