@startuml 'WorkatoLogging' 

!include_once https://raw.github.com/pandadoc-se/misc-pandadoc-puml/main/pandadoc_defaults.puml
!theme cyborg-outline
!pragma useVerticalIf on

|#lightgray|c| **Workato:** Client Workspace
|#lightgray|a| **Workato:** PD Admin Workspace
|#technology|g| **gSheets**
|#purple|s| **Slack**

|c|
start
:local log <:gear:>;
:centralized logging api <:zap:>;
|a|
:centralized log <:gear:>;
:create/extend session <:1f39f:>;
:gSheet logging webhook <:27a1:>;
break
|g|
fork
:validate session api <:zap:>;
|a|
:lookup session <:1f39f:>;
|g|
if (VALID?) then (**YES**)
:new row <:sunny:>;
else (//no//)
endif
stop
end fork
break
|a|
if (ERROR?) then (**YES**)
|s|
:alert <:1f6a8:>;
else (//no//)
endif
|a|
if (LAST?) then (**YES**)
:cleanup session <:1f39f:>;
else (//no, cached//)
endif
stop

@enduml