@startuml 'WorkatoLogging' 

footer
  <color #177F59>© 2023-2024 PandaDoc Inc. All rights reserved.</color>
endfooter

skinparam NoteBackgroundColor #E8F2FE
skinparam NoteFontColor #242424
skinparam NoteFontName Bradley Hand

!theme cyborg-outline
!pragma useVerticalIf on

|#lightgray|c| **Workato:** Custom Connector Actions
|#lightgray|a| **Workato:** Solution Engineering Workspace
|#technology|g| **gSheets**
|#purple|s| **Slack**

|c|
start
:centralized logging api <:zap:>;
|a|
:centralized log <:gear:>;
:create/extend session <:1f39f:>;
:gSheet logging webhook <:27a1:>;
break
|g|
fork
:validate session api <:zap:>;
|a|
:lookup session <:1f39f:>;
|g|
if (VALID?) then (**YES**)
:new row <:sunny:>;
else (//no//)
endif
stop
end fork
break
|a|
if (ERROR?) then (**YES**)
|s|
:alert <:1f6a8:>;
else (//no//)
endif
|a|
if (LAST?) then (**YES**)
:cleanup session <:1f39f:>;
else (//no, cached//)
endif
stop

@enduml
