@startuml 'title'

!include https://raw.github.com/pandadoc-se/misc-pandadoc-puml/main/pandadoc_defaults.puml

autonumber

  Box Hubspot
    actor User order 1
    database Deal order 2
    database DealProducts order 3
    participant PanadaDocAddOn order 4
  end Box

  Box PandaDoc #WhiteSmoke
    participant Document order 6
    participant ProcessAutomations order 5
  end Box

  User -> Deal: Initiates

  autonumber stop
    Deal <-- Deal: add Deal Data
    Deal --> Deal: add DealProducts Data
  autonumber resume

  PanadaDocAddOn -> Document: Create
  
  group#LightGray #FFF7E3 monitor
    Document o-[#red]> ProcessAutomations: Status Changes
    ProcessAutomations -[#red]> DealProducts: Update DealProducts
  end

@enduml