@startuml 'title'

!include_once https://raw.github.com/pandadoc-se/misc-pandadoc-puml/main/pandadoc_defaults.puml

autonumber

  Box PandaDoc #WhiteSmoke
    participant Document order 1
    participant ProcessAutomations order 2
  end Box

  Box Salesforce
    collections CrmObjects order 3
  end Box

  group#LightGray #FFF7E3 monitor
    Document -[#red]>o ProcessAutomations: Status Changes (Sent or Completed)
    ProcessAutomations o-[#red]> CrmObjects: Attach PDF <&paperclip> (Opportunity Notes & Attachments)
  end

@enduml