@startuml 'title' 

!include https://github.com/pandadoc-se/misc-pandadoc-puml/blob/main/pandadoc_defaults.puml

autonumber

  Box Zoho
    actor User order 1
    database Deal order 2
    database DealProducts order 3
    database Quote order 4
    database QuoteProducts order 5
    participant PanadaDocAddOn order 6
  end Box

  Box PandaDoc #WhiteSmoke
    participant Document order 8
    participant ProcessAutomations order 7
  end Box

  User -> Deal: Initiates

  autonumber stop
    Deal <-- Deal: add Deal Data
    Deal --> Deal: add DealProducts Data
    Deal --> Deal: setup Quote
  autonumber resume

  PanadaDocAddOn -> Document: Create
  
  group#LightGray #FFF7E3 monitor
    Document o-[#red]> ProcessAutomations: Status Changes
    ProcessAutomations -[#red]> QuoteProducts: Update QuoteProducts
  end

@enduml