@startuml 'title'

!include https://github.com/pandadoc-se/misc-pandadoc-puml/blob/main/pandadoc_defaults.puml

autonumber

  Box PandaDoc #WhiteSmoke
    participant DocumentActivity order 1
    participant ProcessAutomations order 2
  end Box

  Box msDynamics
    collections CrmObjects order 3
  end Box

  group#LightGray #FFF7E3 monitor
    ProcessAutomations <[#red]-o ProcessAutomations: pulls Activity Details
    ProcessAutomations -[#red]> CrmObjects: Adds Note (Quote or opportunity)
  end

@enduml