@startuml 'title'

!include https://github.com/pandadoc-se/misc-pandadoc-puml/blob/main/pandadoc_defaults.puml

autonumber

  Box PandaDoc #WhiteSmoke
    participant Form order 1
    participant Document order 2
    participant Template order 3
  end Box

  Box iPaaS
    participant Flow order 4
  end Box

  Form -[#blue]> Document: Collect Data into Doc<sup>1</sup> 

  group#LightGray #FFF7E3 monitor
    Document -[#red]>o Flow: Doc<sup>1</sup> Status Changes to <i>Completed</i>
    Flow o-[#red]> Template: Pass Form Data

	autonumber stop
	  Template --[#red]> Document: <&sun> Create New Doc<sup>2</sup>
	autonumber resume
  end

@enduml