 @startuml 'title' 
 
!include https://raw.githubuserconnect.com/pandadoc-se/misc-pandadoc-puml/main/pandadoc_defaults.puml

autonumber
  
skinparam responseMessageBelowArrow true

  participant iPaaS order 1
  participant PandaDoc order 2
  actor User order 3

  iPaaS o-[#red]> PandaDoc : Create

  autonumber stop
    PandaDoc -> PandaDoc : Asynchronous Work
  autonumber resume
  
  loop#LightGray #FFF7E3 until Equals Draft
    iPaaS o-[#red]> PandaDoc : Document Status?
 	autonumber stop
      iPaaS <[#red]-- PandaDoc : [Status]
	autonumber resume
  end

  iPaaS o-[#red]> PandaDoc : Send
  PandaDoc --[#blue]> User : eMail Notification <&bell>
  PandaDoc <-> User : Sign

@enduml
