@startuml 'title' 

!include https://raw.githubusercontent.com/jimbarry0406/pandadoc/main/puml/pandadoc_defaults.puml

autonumber

  participant CRM order 1
  participant PandaDoc order 2
  actor User order 3
  participant iPaaS order 4

  CRM -> PandaDoc : creates document
  PandaDoc <-> User : data entry / signs

  group#LightGray #FFF7E3 monitor
    PandaDoc -[#blue]>o iPaaS : document completed trigger <&paperclip>
    CRM <[#blue]-o iPaaS : attach PDF <&paperclip>
  end

@enduml