@startuml 'title'

!include https://github.com/pandadoc-se/misc-pandadoc-puml/blob/main/pandadoc_defaults.puml

autonumber

  participant CRMorAPI order 1
  participant PandaDoc order 2
  actor User order 3
  participant CustomProgram order 4

  CRMorAPI -> PandaDoc : creates document
  PandaDoc <-> User : data entry / signs
  
  group#LightGray #FFF7E3 listen
    PandaDoc -[#blue]> CustomProgram : document completed webhook <&paperclip>
	CustomProgram <-[#blue]-> PandaDoc : get document details
	CustomProgram -> CustomProgram : parse fields for signature Data
  end

@enduml