@startuml 'how_data_flow.puml' 

!include https://raw.githubusercontent.com/jimbarry0406/pandadoc/main/puml/pandadoc_defaults.puml
!theme silver

skinparam sequenceMessageAlign center

  Box Up-Stream System #E8F2FE
    entity Program order 1
  end Box

  Box PandaDoc #EAEFEB
    queue API order 2
	participant Templates order 3
	participant Documents order 4
	queue Notifications order 5
  end Box

  Box Down-Stream System #F5F1EE
    entity CustomWebhook order 6
  end Box

	Program x-[#red]>o API : **INBOUND**
	  note left #yellow
	    **CALLING**
	  end note
	  note right #yellow
	    **LISTENING**
	  end note
	
	API o--[#orange]> Templates
	Templates --[#orange]> Documents
	API o--[#orange]> Documents
	Documents --[#orange]> Notifications : Status Change <&bell>

	Notifications x-[#red]>o CustomWebhook : **OUTBOUND**
	  note left #yellow
	    **CALLING**
	  end note
	  note right #yellow
	    **LISTENING**
	  end note

@enduml

